package com.matoalot.authsim.model;

public enum LoginState {
    SUCCESS,
    FAILURE_BAD_CREDENTIALS,
    FAILURE_ACCOUNT_LOCKED,
    FAILURE_TOTP_REQUIRED,
    FAILURE_TOTP_INVALID,
    FAILURE_REQUIRE_CAPTCHA,
    FAILURE_UNKNOWN
}
